/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import javax.swing.JTable;
import service.QuicLibService;
import ui.QuicLibePage.AddQuicLib;
import ui.QuicLibePage.MyBookPage;
import ui.QuicLibePage.PagesController;

/**
 *
 * @author Charlos
 */
public class HalUtam extends javax.swing.JFrame {

    private QuicLibService quicLibService;
    private AddQuicLib addQuicLib = new AddQuicLib();
    private JTable tblbook;

    /**
     * Creates new form HalUtam
     */
    public HalUtam() {
        initComponents();

        pnlPage.removeAll();
        pnlPage.add(PagesController.berandaPage);
        repaint();
        revalidate();
    }

    public void setTblbook(JTable tblbook) {
        this.tblbook = tblbook;
    }

    public void setQuicLibService(QuicLibService quicLibService) {
        this.quicLibService = quicLibService;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPage = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        btnBeranda = new javax.swing.JButton();
        btnMyBook = new javax.swing.JButton();
        btnAbout = new javax.swing.JButton();
        btnMyArchive = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPage.setLayout(new javax.swing.BoxLayout(pnlPage, javax.swing.BoxLayout.LINE_AXIS));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(20, 60, 92));
        jLabel1.setForeground(new java.awt.Color(20, 60, 92));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/book_(1).png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Modern No. 20", 1, 30)); // NOI18N
        jLabel2.setText("Quic");

        jLabel3.setFont(new java.awt.Font("Modern No. 20", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(17, 90, 156));
        jLabel3.setText("Lib");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel4.setText("Halo, Welcome!");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(0, 0, 0)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel3))
                    .addComponent(jLabel4))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2))
                    .addComponent(jLabel1))
                .addGap(0, 0, 0)
                .addComponent(jLabel4)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(31, 91, 138));

        jLabel11.setFont(new java.awt.Font("Roboto Black", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(160, 160, 167));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/settings_(1).png"))); // NOI18N
        jLabel11.setText("Pengaturan");

        jLabel13.setFont(new java.awt.Font("Roboto Black", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(160, 160, 167));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/help_(1).png"))); // NOI18N
        jLabel13.setText("Help");

        btnBeranda.setBackground(new java.awt.Color(31, 91, 138));
        btnBeranda.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnBeranda.setForeground(new java.awt.Color(160, 160, 167));
        btnBeranda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/home-icon-silhouette_(1).png"))); // NOI18N
        btnBeranda.setText("Dashboard");
        btnBeranda.setBorderPainted(false);
        btnBeranda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBerandaActionPerformed(evt);
            }
        });

        btnMyBook.setBackground(new java.awt.Color(31, 91, 138));
        btnMyBook.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnMyBook.setForeground(new java.awt.Color(160, 160, 167));
        btnMyBook.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/book_abu.png"))); // NOI18N
        btnMyBook.setText("My Book");
        btnMyBook.setBorderPainted(false);
        btnMyBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMyBookActionPerformed(evt);
            }
        });

        btnAbout.setBackground(new java.awt.Color(31, 91, 138));
        btnAbout.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnAbout.setForeground(new java.awt.Color(160, 160, 167));
        btnAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/info_off.png"))); // NOI18N
        btnAbout.setText("About");
        btnAbout.setBorderPainted(false);
        btnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutActionPerformed(evt);
            }
        });

        btnMyArchive.setBackground(new java.awt.Color(31, 91, 138));
        btnMyArchive.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnMyArchive.setForeground(new java.awt.Color(160, 160, 167));
        btnMyArchive.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/archive_abu.png"))); // NOI18N
        btnMyArchive.setText("My Archive");
        btnMyArchive.setBorderPainted(false);
        btnMyArchive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMyArchiveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMyArchive)
                    .addComponent(btnBeranda)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel13)
                                .addComponent(jLabel11))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btnAbout)
                                .addGap(30, 30, 30))))
                    .addComponent(btnMyBook))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(btnBeranda)
                .addGap(18, 18, 18)
                .addComponent(btnMyBook)
                .addGap(18, 18, 18)
                .addComponent(btnMyArchive)
                .addGap(60, 60, 60)
                .addComponent(jLabel8)
                .addGap(177, 177, 177)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAbout)
                .addGap(0, 21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(pnlPage, javax.swing.GroupLayout.PREFERRED_SIZE, 975, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBerandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBerandaActionPerformed

        PagesController.berandaPage.SetData("/assets/TampilanHome.png");

        pnlPage.removeAll();
        pnlPage.add(PagesController.berandaPage);

        repaint();
        revalidate();


    }//GEN-LAST:event_btnBerandaActionPerformed

    private void btnMyBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyBookActionPerformed
        PagesController.myBookPage.setQuicLibService(quicLibService);
        quicLibService.setTableQuicLib(PagesController.myBookPage.getTable());
        pnlPage.removeAll();
        MyBookPage myBookPage = new MyBookPage();
        quicLibService.setTableQuicLib(myBookPage.getTable());
        myBookPage.setQuicLibService(quicLibService);
        pnlPage.add(myBookPage);
   

        repaint();
        revalidate();
    }//GEN-LAST:event_btnMyBookActionPerformed

    private void btnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutActionPerformed

        PagesController.aboutPage.SetData("/assets/Profile.jpeg", "11S22054", "Charlos Pardomuan Purba");

        pnlPage.removeAll();
        pnlPage.add(PagesController.aboutPage);
        repaint();
        revalidate();
    }//GEN-LAST:event_btnAboutActionPerformed

    private void btnMyArchiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyArchiveActionPerformed

        pnlPage.removeAll();
        pnlPage.add(PagesController.myArchivePage);
        repaint();
        revalidate();
    }//GEN-LAST:event_btnMyArchiveActionPerformed

    /**
     * M
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HalUtam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HalUtam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HalUtam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HalUtam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HalUtam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbout;
    private javax.swing.JButton btnBeranda;
    private javax.swing.JButton btnMyArchive;
    private javax.swing.JButton btnMyBook;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel pnlPage;
    // End of variables declaration//GEN-END:variables
}
