/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.QuicLibePage;

import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import service.QuicLibService;

/**
 *
 * @author Charlos
 */
public class MyBookPage extends javax.swing.JPanel {

    private DetailQuicLib detailQuicLib = new DetailQuicLib();
    private QuicLibService quicLibService;
    private AddQuicLib addQuicLib = new AddQuicLib();
    private ArchiveQuicLib archiveQuicLib = new ArchiveQuicLib();

    /**
     * Creates new form MyBook
     */
    public MyBookPage() {
        initComponents();
        repaint();
        revalidate();
    }

    public void setQuicLibService(QuicLibService quicLibService) {
        this.quicLibService = quicLibService;
    }

    public JTable getTable() {
        return tabelLib;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelLib = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cbxStatus = new javax.swing.JComboBox<>();
        btnSearch = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnAddMyBook1 = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnArchiveMyBook = new javax.swing.JButton();

        tabelLib.setAutoCreateRowSorter(true);
        tabelLib.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ISBN", "JUDUL", "GENRE", "STATUS", "AKSI"
            }
        ));
        tabelLib.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tabelLibMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabelLib);

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(29, 59, 95));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("My QuicLib");

        cbxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semua", "Belum Diarsipkan", "Diarsipkan" }));
        cbxStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxStatusActionPerformed(evt);
            }
        });

        btnSearch.setBackground(new java.awt.Color(29, 59, 95));
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Cari");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(29, 59, 95));
        jLabel2.setText("Daftar QuicLib");

        btnAddMyBook1.setBackground(new java.awt.Color(31, 91, 138));
        btnAddMyBook1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnAddMyBook1.setForeground(new java.awt.Color(255, 255, 255));
        btnAddMyBook1.setText("Add MyBook");
        btnAddMyBook1.setBorderPainted(false);
        btnAddMyBook1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMyBook1ActionPerformed(evt);
            }
        });

        btnReset.setBackground(new java.awt.Color(31, 91, 138));
        btnReset.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setText("Reset");
        btnReset.setBorderPainted(false);
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnArchiveMyBook.setBackground(new java.awt.Color(31, 91, 138));
        btnArchiveMyBook.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnArchiveMyBook.setForeground(new java.awt.Color(255, 255, 255));
        btnArchiveMyBook.setText("Archive MyBook");
        btnArchiveMyBook.setBorderPainted(false);
        btnArchiveMyBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArchiveMyBookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnArchiveMyBook, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAddMyBook1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtSearch)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSearch))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1074, Short.MAX_VALUE))
                        .addGap(74, 74, 74))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel1)
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 60, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 423, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddMyBook1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnArchiveMyBook, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddMyBook1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMyBook1ActionPerformed

        addQuicLib = new AddQuicLib();
        if (addQuicLib != null) {
            addQuicLib.dispose();
        }
        addQuicLib.setQuicLibService(quicLibService);
        addQuicLib.setVisible(true);
        quicLibService.setTableQuicLib(tabelLib);
    }//GEN-LAST:event_btnAddMyBook1ActionPerformed

    private void tabelLibMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelLibMouseReleased

        int row = tabelLib.rowAtPoint(evt.getPoint());
        int col = tabelLib.columnAtPoint(evt.getPoint());

        if (row >= 0 && col == 0) {
            int selectedISBN = (int) tabelLib.getValueAt(row, 0);
            String selectedJUDUL = tabelLib.getValueAt(row, 1).toString();
            String selectedGENRE = tabelLib.getValueAt(row, 2).toString();
            int selectedJUMLAH_HALAMAN = (int) tabelLib.getValueAt(row, 3);
            boolean selectedSTATUS = tabelLib.getValueAt(row, 4).toString().equals("Diarsipkan");

            DetailQuicLib detailQuicLib = new DetailQuicLib(selectedISBN, selectedJUDUL, selectedGENRE, selectedJUMLAH_HALAMAN, selectedSTATUS);
            if (detailQuicLib.isVisible() == true) {
                detailQuicLib.dispose();
            } else {
                detailQuicLib.setVisible(true);
            }
        }
    }//GEN-LAST:event_tabelLibMouseReleased

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed

        String keyword = txtSearch.getText();
        quicLibService.setTableQuicLib(tabelLib);
        quicLibService.showQuicLib(keyword, null);


    }//GEN-LAST:event_btnSearchActionPerformed

    private void cbxStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxStatusActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed

        quicLibService.showQuicLib("", null);

    }//GEN-LAST:event_btnResetActionPerformed

    private void btnArchiveMyBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArchiveMyBookActionPerformed
        archiveQuicLib = new ArchiveQuicLib();
        if (archiveQuicLib != null) {
            archiveQuicLib.dispose();
        }
        archiveQuicLib.setQuicLibService(quicLibService);
        archiveQuicLib.setVisible(true);
        quicLibService.setTableQuicLib(tabelLib);
    }//GEN-LAST:event_btnArchiveMyBookActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyBookPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyBookPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyBookPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyBookPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyBookPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddMyBook1;
    private javax.swing.JButton btnArchiveMyBook;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cbxStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelLib;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

}
